Resources:
  S3DataLakeProcessing:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: ${self:custom.prefix}-processing
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: aws:kms
              KMSMasterKeyID: !Ref DataLakeEncryptionKey
      LoggingConfiguration:
        DestinationBucketName: !Ref S3BucketDataLakeLogs
        LogFilePrefix: ${self:custom.logFilePrefix}/processing/log-
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
            - Id: StandartIARule
              Status: Enabled
              Transitions:
                - TransitionInDays: '30'
                  StorageClass: STANDARD_IA

Outputs:
  S3DataLakeProcessingName:
    Value: !Ref S3DataLakeProcessing
    Export:
      Name: ${self:custom.prefix}-S3DataLakeProcessingName

  S3DataLakeProcessingArn:
    Value: !GetAtt S3DataLakeProcessing.Arn
    Export:
      Name: ${self:custom.prefix}-S3DataLakeProcessingArn
